### ISSUE TITLE
<feat> Required "Separate Sorting Algorithm Section"

### ISSUE THREAD

**Issue by manikanta-parameshwarappa** [SayuruRehan/HackFest23#3]
@SayuruRehan 
can i contribute ? if possible can you add " hacktoberfest-2023 labels " to it .
<html>
<img src="https://media.tenor.com/HPht2t341E8AAAAC/puppy-dog-eyes-sad.gif">
</html>

**Comment by SayuruRehan** [comment]
Yes! @manikanta-manii you can. Will go through the PR and provide approval. No need of issues in this case hence closing this
